spring.application.name=erurekaserver

server.port=8761


# eureka server itself won't register with itself so values should be false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
