
spring.kafka.bootstrap-servers=192.168.0.34:9092
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.application.name=payment
server.port=8082

logging.level.org.apache.kafka=DEBUG

spring.kafka.consumer.group-id=payment-group
spring.kafka.consumer.auto-offset-reset=earliest

management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
logging.pattern.level=%5p [${spring.application.name}, traceId=%X{trace_id}, spanId=%X{span_id}]
management.endpoints.web.exposure.include=*
management.observations.http.server.requests.enabled=true

