spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9093}

# CORS
cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:3000,https://yourdomain.com}

# Logging
logging.level.root=WARN
logging.level.com.paymentservice=INFO
logging.file.name=/var/log/payment-microservice.log
