
#logging.level.org.apache.kafka=DEBUG
spring.datasource.url=jdbc:mysql://localhost:3306/msrevision?createDatabaseIfNotExists=true&useSSL=false&allowPublicKeyRetrieval=true
spring.jpa.properties.hibernate.default_schema=msrevision
spring.datasource.username=root
spring.datasource.password=Anand11@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Eureka client configuration


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true


# Kafka bootstrap server
spring.kafka.bootstrap-servers=192.168.0.34:9092

management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
logging.pattern.level=%5p [${spring.application.name}, traceId=%X{trace_id}, spanId=%X{span_id}]
management.endpoints.web.exposure.include=*
management.observations.http.server.requests.enabled=true

