spring.application.name=order-microservice
server.port=8081

spring.profiles.active=localhost


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

